
services:  
  eureka:
    image: eureka
    container_name: eureka
    hostname: eureka
    ports:
      - 8761:8761

  configserver:
    image: configserver
    container_name: configserver
    hostname: configserver
    ports: 
      - "8888:8888"
    depends_on:
      - eureka
      
  customers:
    image: customers
    container_name: customer
    hostname: customer
    ports:
      - "8081:8081"
    depends_on:
      - configserver
      - eureka

  products:
    image: products
    container_name: product
    hostname: customer
    ports:
      - "8082:8082"
    depends_on:
      - configserver
      - eureka

  # orderQueue:
  #   image: rabbitmq:management
  #   container_name: orderQueue
  #   hostname: orderQueue
  #   ports:
  #     - "5672:5672"  # AMQP
  #     - "15672:15672" # RabbitMQ Management UI
  #   environment:
  #     RABBITMQ_DEFAULT_USER: guest
  #     RABBITMQ_DEFAULT_PASS: guest

  # orderpub:
  #   image: orderpub
  #   container_name: orderpub
  #   depends_on:
  #     - orderQueue
  #   environment:
  #     SPRING_RABBITMQ_HOST: orderQueue
  #     SPRING_RABBITMQ_PORT: 5672
  #     SPRING_RABBITMQ_USERNAME: guest
  #     SPRING_RABBITMQ_PASSWORD: guest
  #   ports:
  #     - "8083:8083"

  # ordersub:
  #   image: ordersub
  #   container_name: ordersub
  #   depends_on:
  #     - orderQueue
  #   environment:
  #     SPRING_RABBITMQ_HOST: orderQueue
  #     SPRING_RABBITMQ_PORT: 5672
  #     SPRING_RABBITMQ_USERNAME: guest
  #     SPRING_RABBITMQ_PASSWORD: guest
  #   ports:
  #     - "8084:8084"